# Generated by Django 4.2.1 on 2023-09-01 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 15, 45, 24, 248040, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2023, 9, 1, 15, 45, 24, 268397, tzinfo=datetime.timezone.utc), help_text="When do you want to reach your saving's goal?"),
        ),
    ]
